import Link from "next/link";
import { ClipboardList, FileText, MessageSquareText, UserRound, Users } from "lucide-react";
import DoctorShell from "@/components/DoctorShell";
import JourneyStateControl from "@/components/JourneyStateControl";
import Timeline from "@/components/Timeline";
import { api } from "@/lib/api";
import { fmtDate } from "@/lib/format";
export const dynamic="force-dynamic";
const tabs=[
 ["Overview","overview"],["Care Journey","care-journey"],["Care Plan","care-plan"],["Medications","medications"],["Treatments","treatments"],["Investigations","investigations"],["Reports","reports"],["Appointments","appointments"],["Milestones","milestones"],["Queries","queries"],["Caregiver & Consent","caregiver-consent"]
] as const;
export default async function Patient360Page({params}:{params:{id:string}}){
 const d=await api.patient360(params.id),p=d.patient;
 const byType=(type:string)=>d.timeline.filter(e=>e.type===type);
 const appointments=byType("APPOINTMENT"),medications=byType("MEDICATION"),treatments=byType("TREATMENT"),investigations=byType("INVESTIGATION"),milestones=byType("MILESTONE");
 return <DoctorShell>
  <section className="onko-card overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-5 p-6"><div className="flex gap-4"><div className="grid h-16 w-16 place-items-center rounded-full bg-onko-softteal text-onko-teal"><UserRound size={30}/></div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-[30px] font-bold tracking-tight sm:text-[34px]">{p.name}</h1><span className="onko-chip bg-onko-teal text-white">{p.journey_state.replaceAll("_"," ").toLowerCase()}</span></div><p className="mt-1 text-[15px] text-onko-muted">{p.age} yrs · {p.gender} · {p.diagnosis_label}</p><p className="mt-2 text-[15px] font-semibold">{p.regimen_label} · Cycle {p.cycle_current} of {p.cycle_total}</p></div></div><Link href={"/doctor/careplan/"+p.id} className="onko-button-primary"><ClipboardList size={16}/>Edit Care Plan</Link></div>
   <nav className="flex gap-1 overflow-x-auto border-t border-onko-line px-5 py-2 text-[14px] font-semibold">{tabs.map(([label,id],i)=><a key={id} href={"#"+id} className={"whitespace-nowrap rounded-lg px-3 py-2 "+(i===0?"bg-onko-teal text-white":"text-onko-muted hover:bg-onko-softteal")}>{label}</a>)}</nav>
  </section>
  <section id="overview" className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="grid gap-5"><div className="onko-card p-5"><p className="onko-eyebrow">Since your last review</p><h2 className="mt-1 text-[24px] font-bold">Recorded changes</h2><div className="mt-4 grid gap-2">{d.since_last_review.bullets.map(b=><div key={b} className="rounded-xl bg-onko-softteal/60 px-4 py-3 text-[15px]">{b}</div>)}</div></div><section id="care-journey" className="onko-card scroll-mt-24 p-5"><h2 className="text-[24px] font-bold">Care Journey</h2><div className="mt-4"><Timeline events={d.timeline}/></div></section></div>
   <aside className="grid content-start gap-4"><div className="onko-card p-5"><p className="onko-eyebrow">Pre-consultation brief</p><h2 className="mt-1 text-[20px] font-bold">Review snapshot</h2><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-onko-softteal/60 p-3"><p className="text-[12px] text-onko-muted">Changes</p><p className="mt-1 text-[22px] font-bold">{d.since_last_review.bullets.length}</p></div><div className="rounded-xl bg-onko-softteal/60 p-3"><p className="text-[12px] text-onko-muted">Open queries</p><p className="mt-1 text-[22px] font-bold">{d.open_queries.length}</p></div><div className="rounded-xl bg-onko-softteal/60 p-3"><p className="text-[12px] text-onko-muted">New reports</p><p className="mt-1 text-[22px] font-bold">{d.reports.filter(r=>!r.reviewed).length}</p></div><div className="rounded-xl bg-onko-softteal/60 p-3"><p className="text-[12px] text-onko-muted">Attention</p><p className="mt-1 text-[22px] font-bold">{d.attention.length}</p></div></div><p className="mt-3 text-[12px] leading-5 text-onko-muted">Recorded activity only. Clinical interpretation remains with the care team.</p></div><div className="grid grid-cols-3 gap-2"><div className="onko-card p-4"><FileText size={17} className="text-onko-teal"/><p className="mt-2 text-[30px] font-bold">{d.reports.length}</p><p className="text-[13px] text-onko-muted">Reports</p></div><div className="onko-card p-4"><MessageSquareText size={17} className="text-onko-teal"/><p className="mt-2 text-[30px] font-bold">{d.open_queries.length}</p><p className="text-[13px] text-onko-muted">Queries</p></div><div className="onko-card p-4"><Users size={17} className="text-onko-teal"/><p className="mt-2 text-[30px] font-bold">{d.caregivers.length}</p><p className="text-[13px] text-onko-muted">Caregivers</p></div></div></aside></section>
  <section id="care-plan" className="onko-card mt-5 scroll-mt-24 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-[24px] font-bold">Approved Care Plan</h2><p className="mt-1 text-[14px] text-onko-muted">Clinician-approved care-plan items recorded for this patient.</p></div><Link href={"/doctor/careplan/"+p.id} className="onko-button-secondary">Open Care Plan</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{d.care_plan.length?d.care_plan.map(x=><div key={x.id} className="rounded-xl bg-onko-surface p-4"><div className="flex justify-between gap-3"><strong>{x.title}</strong><span className="onko-chip bg-white text-onko-muted">{x.type.toLowerCase()}</span></div><p className="mt-2 text-[13px] text-onko-muted">{fmtDate(x.start_date)}{x.end_date?" → "+fmtDate(x.end_date):""}</p></div>):<Empty/>}</div></section><div className="mt-5 grid gap-5 xl:grid-cols-2">
   <EventSection id="medications" title="Medications" items={medications}/><EventSection id="treatments" title="Treatments" items={treatments}/><EventSection id="investigations" title="Investigations" items={investigations}/><EventSection id="appointments" title="Appointments" items={appointments}/><EventSection id="milestones" title="Milestones" items={milestones}/>
   <section id="reports" className="onko-card scroll-mt-24 p-5"><h2 className="text-[20px] font-bold">Reports</h2><div className="mt-3 grid gap-3">{d.reports.length?d.reports.map(r=><div key={r.id} className="rounded-xl bg-onko-surface p-4 text-[15px]"><div className="flex justify-between gap-2"><strong>{r.title}</strong><span className="text-[13px] text-onko-muted">{fmtDate(r.uploaded_at)}</span></div>{r.extracted_values.map(v=><p key={v.name} className="mt-2 text-onko-muted">{v.name}: {v.value} {v.unit}</p>)}</div>):<Empty/>}</div></section>
   <section id="queries" className="onko-card scroll-mt-24 p-5"><h2 className="text-[20px] font-bold">Open Queries</h2><div className="mt-3 grid gap-3">{d.open_queries.length?d.open_queries.map(q=><div key={q.id} className="rounded-xl bg-onko-surface p-4"><p className="text-[12px] font-semibold uppercase text-onko-muted">{q.category.replaceAll("_"," ").toLowerCase()} · {q.channel}</p><p className="mt-2 text-[15px]">{q.summary}</p><p className="mt-2 text-[12px] text-onko-muted">Status: {q.status}</p></div>):<Empty/>}</div></section>
   <section id="caregiver-consent" className="onko-card scroll-mt-24 p-5 xl:col-span-2"><h2 className="text-[20px] font-bold">Caregiver & Consent</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{d.caregivers.length?d.caregivers.map(c=><div key={c.id} className="rounded-xl bg-onko-surface p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{c.name}</strong><span className="onko-chip bg-onko-softteal text-onko-teal">{c.consent_status.toLowerCase()}</span></div><p className="mt-1 text-[13px] text-onko-muted">{c.relation} · {c.type}</p><div className="mt-3 flex flex-wrap gap-2 text-[12px] text-onko-muted">{c.permissions.view_journey&&<span className="rounded-full bg-white px-2 py-1">View journey</span>}{c.permissions.upload_reports&&<span className="rounded-full bg-white px-2 py-1">Upload reports</span>}{c.permissions.receive_escalations&&<span className="rounded-full bg-white px-2 py-1">Receive escalations</span>}</div></div>):<Empty/>}</div></section>
  </div>
 </DoctorShell>
}
function EventSection({id,title,items}:{id:string;title:string;items:any[]}){return <section id={id} className="onko-card scroll-mt-24 p-5"><h2 className="text-[20px] font-bold">{title}</h2><div className="mt-3 grid gap-2">{items.length?items.map(e=><div key={e.id} className="rounded-xl bg-onko-surface p-4"><div className="flex items-start justify-between gap-3"><strong className="text-[15px]">{e.title}</strong><span className="text-[12px] text-onko-muted">{fmtDate(e.scheduled_at)}</span></div><p className="mt-1 text-[13px] text-onko-muted">{e.status.replaceAll("_"," ").toLowerCase()}</p></div>):<Empty/>}</div></section>}
function Empty(){return <p className="text-[14px] text-onko-muted">No recorded items.</p>}
