import Link from "next/link";
import { FileText } from "lucide-react";
import DoctorShell from "@/components/DoctorShell";
import { api } from "@/lib/api";
import { fmtDate } from "@/lib/format";
export const dynamic="force-dynamic";
export default async function ReportsPage(){const patients=await api.patients();const data=(await Promise.all(patients.map(async p=>({p,d:await api.patient360(p.id)})))).flatMap(({p,d})=>d.reports.map(r=>({p,r})));return <DoctorShell>
<p className="onko-eyebrow text-onko-teal">Recorded documents</p><h1 className="mt-2 text-[44px] font-bold tracking-tight">Reports</h1><p className="mt-2 max-w-3xl text-[16px] leading-7 text-onko-muted">Uploaded reports and extracted values are displayed as recorded. OnKo does not interpret results or mark values clinically normal or abnormal.</p>
<div className="mt-7 grid gap-4">{data.length?data.map(({p,r})=><article key={r.id} className="onko-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><span className="grid h-12 w-12 place-items-center rounded-xl bg-onko-softteal text-onko-teal"><FileText size={21}/></span><div><h2 className="text-[20px] font-bold">{r.title}</h2><Link href={"/doctor/patients/"+p.id} className="mt-1 block text-[14px] font-semibold text-onko-teal">{p.name}</Link></div></div><span className={"onko-chip "+(r.reviewed?"bg-onko-softteal text-onko-teal":"bg-onko-amberbg text-onko-amber")}>{r.reviewed?"Reviewed":"Awaiting review"}</span></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{r.extracted_values.map(v=><div key={v.name} className="rounded-xl bg-onko-surface p-5"><p className="text-[13px] font-bold text-onko-muted">{v.name}</p><p className="mt-1 text-[21px] font-bold">{v.value} <span className="text-[14px] font-medium text-onko-muted">{v.unit}</span></p><p className="mt-2 text-[13px] leading-5 text-onko-muted">Printed reference: {v.reference_range_as_printed}<br/>Source: {v.source_line}</p></div>)}</div><p className="mt-4 text-[13px] text-onko-muted">Uploaded by {r.uploaded_by_role} · {fmtDate(r.uploaded_at)}</p></article>):<div className="onko-card p-6 text-[15px] text-onko-muted">No reports recorded.</div>}</div>
</DoctorShell>}
