"use client";
import { useState } from "react";
import { Check, FlaskConical, Sparkles } from "lucide-react";
import DoctorShell from "@/components/DoctorShell";
import { api } from "@/lib/api";
import type { CarePlanDraft,CopilotItem,EventType } from "@/lib/types";
const TYPES:EventType[]=["MEDICATION","INVESTIGATION","TREATMENT","APPOINTMENT","MILESTONE"];
export default function CopilotPage({params}:{params:{id:string}}){
 const [text,setText]=useState(""),[draft,setDraft]=useState<CarePlanDraft|null>(null),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false);
 const edit=(i:number,patch:Partial<CopilotItem>)=>draft&&setDraft({...draft,items:draft.items.map((it,j)=>j===i?{...it,...patch}:it)});
 return <DoctorShell><div className="max-w-[1180px]">
  <section className="onko-card overflow-hidden"><div className="flex items-center justify-between border-b border-onko-line bg-onko-softteal/55 px-5 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[.1em] text-onko-teal">Care Plan Copilot · Human-governed workflow structuring</p><h1 className="mt-1 text-[24px] font-bold">Structure an Already-Decided Plan</h1></div><span className="onko-chip bg-white text-onko-teal">Zero diagnostic generation</span></div>
  <div className="p-5"><p className="text-[11px] font-bold uppercase tracking-[.08em] text-onko-muted">Doctor&apos;s dictated / typed clinical entry</p><textarea value={text} onChange={e=>setText(e.target.value)} rows={4} placeholder="CBC before chemotherapy on 24 Sept. Capecitabine 500mg BID with food for 14 days..." className="mt-2 w-full rounded-xl border border-onko-line bg-onko-surface p-4 text-[14px] leading-6 outline-none focus:border-onko-teal"/>
  <div className="mt-3 flex justify-end"><button disabled={busy||!text} onClick={async()=>{setBusy(true);setDraft(await api.createDraft(params.id,text));setBusy(false)}} className="onko-button-primary disabled:opacity-50"><Sparkles size={15}/>{busy?"Structuring…":"Structure Plan (Done)"}</button></div></div></section>
  {draft&&<section className="mt-6"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.1em] text-violet-700">Draft workflow stage</p><h2 className="mt-1 text-[19px] font-bold">{draft.items.length} items structured from your input. Review, adjust, or reclassify below.</h2></div><span className="onko-chip bg-onko-amberbg text-onko-amber">Requires clinician approval</span></div>
  <div className="grid gap-3">{draft.items.map((it,i)=><article key={i} className="onko-card p-5"><div className="grid gap-4 lg:grid-cols-[180px_1fr_170px_170px]"><label className="text-[11px] font-bold uppercase text-onko-muted">Type<select value={it.type} onChange={e=>edit(i,{type:e.target.value as EventType})} className="mt-2 w-full rounded-lg border border-onko-line p-2.5 text-[13px]">{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label className="text-[11px] font-bold uppercase text-onko-muted">Workflow item<input value={it.title} onChange={e=>edit(i,{title:e.target.value})} className="mt-2 w-full rounded-lg border border-onko-line p-2.5 text-[13px]"/></label><label className="text-[11px] font-bold uppercase text-onko-muted">Start<input type="date" value={it.start_date} onChange={e=>edit(i,{start_date:e.target.value})} className="mt-2 w-full rounded-lg border border-onko-line p-2.5 text-[13px]"/></label><label className="text-[11px] font-bold uppercase text-onko-muted">End<input type="date" value={it.end_date??""} onChange={e=>edit(i,{end_date:e.target.value||null})} className="mt-2 w-full rounded-lg border border-onko-line p-2.5 text-[13px]"/></label></div><div className="mt-4 flex gap-2 rounded-xl bg-onko-softteal/60 p-3 text-[12px] text-onko-muted"><FlaskConical size={15} className="shrink-0 text-onko-teal"/><span><strong>Extracted from doctor input:</strong> “{it.source_span}”</span></div></article>)}</div>
  <div className="mt-4 flex justify-end"><button disabled={approved} onClick={async()=>{await api.updateDraft(draft.id,draft.items);await api.approveDraft(draft.id);setApproved(true)}} className="onko-button-primary disabled:opacity-60"><Check size={15}/>{approved?"Plan approved — added to journey":"Approve plan"}</button></div></section>}
 </div></DoctorShell>
}
