"use client";
import {useState} from "react";
import {Clock3,Link2,ShieldCheck,UserRoundCheck,UserRoundX} from "lucide-react";
import type {Caregiver} from "@/lib/types";
export default function CaregiverLifecycle({caregiver}:{caregiver:Caregiver}){
 const [state,setState]=useState<Caregiver["consent_status"]>(caregiver.consent_status),[temporary,setTemporary]=useState(false);
 return <section className="rounded-3xl bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="onko-eyebrow">Caregiver lifecycle</p><h2 className="mt-1 text-[22px] font-bold">Invitation & access state</h2><p className="mt-1 text-[13px] text-onko-muted">Patient-controlled prototype states for invitation, consent and revocation.</p></div><span className={"rounded-full px-3 py-1.5 text-[12px] font-bold "+(state==="GRANTED"?"bg-onko-softteal text-onko-teal":state==="PENDING"?"bg-onko-amberbg text-onko-amber":"bg-red-50 text-onko-sos")}>{state}</span></div>
 <div className="mt-5 grid gap-3 sm:grid-cols-3"><State icon={<Link2 size={18}/>} title="Invited" active={state==="PENDING"}/><State icon={<UserRoundCheck size={18}/>} title="Consent granted" active={state==="GRANTED"}/><State icon={<UserRoundX size={18}/>} title="Access revoked" active={state==="REVOKED"}/></div>
 <div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>setState("PENDING")} className="onko-button-secondary">Preview pending</button><button onClick={()=>setState("GRANTED")} className="onko-button-secondary">Preview granted</button><button onClick={()=>setState("REVOKED")} className="onko-button-secondary text-onko-sos">Preview revoked</button></div>
 <div className="mt-5 rounded-2xl bg-onko-surface p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-3"><Clock3 className="mt-0.5 text-onko-teal" size={19}/><div><strong className="text-[14px]">Temporary caregiver access</strong><p className="mt-1 text-[12px] text-onko-muted">Prototype an access window without changing the permanent caregiver.</p></div></div><button onClick={()=>setTemporary(v=>!v)} className="onko-button-secondary">{temporary?"End temporary access":"Enable temporary access"}</button></div>{temporary&&<p className="mt-3 rounded-xl bg-white p-3 text-[12px] text-onko-muted">Temporary access preview active · expiry would be enforced by the backend consent service.</p>}</div>
 <div className="mt-4 flex gap-3 rounded-xl bg-onko-softteal/60 p-4"><ShieldCheck size={18} className="shrink-0 text-onko-teal"/><p className="text-[12px] leading-5 text-onko-muted">These controls are UI-only. A caregiver can never grant themselves access; persisted consent must come from the patient.</p></div></section>}
function State({icon,title,active}:{icon:React.ReactNode;title:string;active:boolean}){return <div className={"rounded-2xl border p-4 "+(active?"border-onko-teal bg-onko-softteal":"border-onko-line bg-white")}><span className={active?"text-onko-teal":"text-onko-muted"}>{icon}</span><p className="mt-3 text-[13px] font-bold">{title}</p></div>}