"use client";
import {useState} from "react";
import {Check,ChevronLeft,ChevronRight,KeyRound,MessageCircle,Phone,ShieldCheck,X} from "lucide-react";
import ABHAConnection from "@/components/ABHAConnection";
import type {Patient} from "@/lib/types";
const steps=["Welcome","Verify","Review","Preferences","Ready"];
export default function PatientFirstAccess({patient}:{patient:Patient}){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0),[verified,setVerified]=useState(false),[consent,setConsent]=useState(false),[language,setLanguage]=useState(patient.preferred_language),[whatsapp,setWhatsapp]=useState(true),[done,setDone]=useState(false);
 return <><button onClick={()=>{setStep(0);setOpen(true)}} className="onko-button-secondary mt-3">Preview first-time setup</button>{open&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/35 p-3 sm:p-6"><div className="mx-auto my-4 w-full max-w-2xl rounded-3xl bg-white shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="first-access-title"><div className="flex justify-between border-b border-onko-line p-5 sm:p-7"><div><p className="onko-eyebrow">First-time access</p><h2 id="first-access-title" className="mt-1 text-[24px] font-bold">Welcome to OnKo, {patient.name.split(" ")[0]}</h2></div><button onClick={()=>setOpen(false)} aria-label="Close first-time setup"><X/></button></div><div className="flex overflow-x-auto border-b border-onko-line px-5 py-4">{steps.map((s,i)=><div key={s} className="flex min-w-[105px] flex-1 items-center"><span className={"grid h-7 w-7 place-items-center rounded-full text-[11px] font-bold "+(i<step?"bg-onko-teal text-white":i===step?"bg-onko-softteal text-onko-teal ring-2 ring-onko-teal":"bg-onko-surface text-onko-muted")}>{i<step?<Check size={13}/>:i+1}</span><span className="ml-2 text-[11px] font-semibold">{s}</span></div>)}</div><div className="p-5 sm:p-7">
 {step===0&&<div><h3 className="text-[21px] font-bold">Your care journey is ready</h3><p className="mt-2 text-[14px] leading-6 text-onko-muted">Your care team has created your OnKo profile and recorded your care information. OnKo helps you stay connected to that journey; it does not diagnose you or make treatment decisions.</p><div className="mt-5 rounded-2xl bg-onko-softteal p-4"><strong>{patient.regimen_label}</strong><p className="mt-1 text-[13px] text-onko-muted">Current cycle: {patient.cycle_current} of {patient.cycle_total} · recorded by your care team</p></div></div>}
 {step===1&&<div><h3 className="text-[21px] font-bold">Verify your number</h3><p className="mt-2 text-[14px] text-onko-muted">We will verify the number your care team registered: <strong className="text-onko-ink">{patient.phone_whatsapp}</strong></p>{!verified?<div className="mt-5 rounded-2xl bg-onko-surface p-5"><div className="flex gap-3"><Phone className="text-onko-teal"/><p className="text-[13px] leading-5 text-onko-muted">Enter the OTP sent to this number. This prototype does not send a real OTP.</p></div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input inputMode="numeric" maxLength={6} aria-label="OTP" placeholder="6-digit OTP" className="flex-1 rounded-xl border border-onko-line bg-white p-3 tracking-[.3em]"/><button onClick={()=>setVerified(true)} className="onko-button-primary">Verify</button></div></div>:<div className="mt-5 flex gap-3 rounded-xl bg-onko-softteal p-4"><ShieldCheck className="text-onko-teal"/><strong className="text-onko-teal">Number verified</strong></div>}</div>}
 {step===2&&<div><h3 className="text-[21px] font-bold">Review care information</h3><p className="mt-2 text-[13px] leading-6 text-onko-muted">This is clinician-recorded information. If something looks incorrect, contact your care team rather than editing the clinical plan yourself.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Review label="Diagnosis" value={patient.diagnosis_label}/><Review label="Regimen" value={patient.regimen_label}/><Review label="Current cycle" value={patient.cycle_current+" of "+patient.cycle_total}/><Review label="Journey state" value={patient.journey_state.replaceAll("_"," ").toLowerCase()}/></div><div className="mt-4"><ABHAConnection abhaId={patient.abha_id}/></div></div>}
 {step===3&&<div><h3 className="text-[21px] font-bold">Communication & consent</h3><div className="mt-5 grid gap-4"><label className="text-[13px] font-semibold">Preferred language<select value={language} onChange={e=>setLanguage(e.target.value)} className="mt-2 w-full rounded-xl border border-onko-line bg-white p-3"><option>English</option><option>Hindi</option><option>Telugu</option></select></label><button onClick={()=>setWhatsapp(v=>!v)} className={"flex items-center justify-between rounded-xl border p-4 text-left "+(whatsapp?"border-onko-teal bg-onko-softteal":"border-onko-line")}><span className="flex gap-3"><MessageCircle className="text-onko-teal"/><span><strong className="block text-[14px]">WhatsApp care check-ins</strong><span className="text-[12px] text-onko-muted">Daily consolidated journey prompts on your verified number.</span></span></span><span className="text-[12px] font-bold text-onko-teal">{whatsapp?"ON":"OFF"}</span></button><label className="flex cursor-pointer items-start gap-3 rounded-xl bg-onko-surface p-4 text-[13px] leading-5"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1"/><span>I understand that OnKo organizes recorded care activity and communication. Clinical decisions remain with my care team, and caregiver/data-sharing access remains under my consent.</span></label></div></div>}
 {step===4&&<div className="text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-onko-softteal text-onko-teal"><KeyRound/></span><h3 className="mt-4 text-[22px] font-bold">Your OnKo access is ready</h3><p className="mx-auto mt-2 max-w-md text-[13px] leading-6 text-onko-muted">In production, your verified activation link/login setup is delivered securely to your registered number. Your care journey then opens with the information approved by your care team.</p>{done&&<p className="mt-4 rounded-xl bg-onko-softteal p-3 text-[13px] font-semibold text-onko-teal">First-time setup preview completed.</p>}</div>}
 </div><div className="flex justify-between gap-3 border-t border-onko-line p-5 sm:px-7"><button disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} className="onko-button-secondary disabled:opacity-40"><ChevronLeft size={15}/>Back</button>{step<4?<button disabled={(step===1&&!verified)||(step===3&&!consent)} onClick={()=>setStep(s=>Math.min(4,s+1))} className="onko-button-primary disabled:opacity-40">Continue<ChevronRight size={15}/></button>:<button onClick={()=>{window.localStorage.setItem("onko-language",language);window.dispatchEvent(new Event("onko-language-change"));setDone(true)}} className="onko-button-primary">Enter OnKo</button>}</div></div></div>}</>}
function Review({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-onko-surface p-4"><p className="text-[11px] font-bold uppercase text-onko-muted">{label}</p><p className="mt-1 text-[14px] font-semibold capitalize">{value}</p></div>}